[package]
name = "filesets"
version = "0.1.0"
authors = ["Bryce Covert <bryce@pelo.tech>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
tokio-fs ="0.1.6"
futures = "0.1.26"
rust-crypto = "^0.2"
threadpool = "1.7.1"
pbr = "1.0.1"

[profile.release]
lto = true
panic = 'abort'


